# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_testing_simon',
                'doc_host': 'https://Muhammad Asif.github.io',
                'git_url': 'https://github.com/Muhammad Asif/nbdev_testing_simon',
                'lib_path': 'nbdev_testing_simon'},
  'syms': {'nbdev_testing_simon.core': {}}}
