"""AI Board Scanner using nbdev"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/index.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/index.ipynb 0
#| export
#| default_exp core

# %% ../nbs/index.ipynb 15
1+1
